version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "11:15"
    commit-message:
      prefix: "[actions] "
    groups:
      action-dependencies:
        patterns:
          - "*"
