version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: # UTC
      interval: "weekly"
      day: "wednesday"
      time: "23:15"
    commit-message:
      prefix: "[actions] "
    labels:
      - "actions"
    groups:
      action-dependencies:
        patterns:
          - "*"
