name: "Auto Delete CI"

on:
  pull_request:
    types: [closed]

jobs:
  auto-delete:
    runs-on: ubuntu-latest
    if: |
      contains(fromJSON('["nixos", "actions"]'), github.event.pull_request.labels.*.name)
      && github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4.1.7
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push -d origin ${{ github.event.pull_request.head.ref }}
