name: "Auto Delete CI"

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  auto-delete:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'nixos')
      || contains(github.event.pull_request.labels.*.name, 'actions')
    steps:
      - uses: actions/checkout@v4.1.7
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push -d origin ${{ github.event.pull_request.head.ref }}
