name: "Nix-Flake Updates"

on:
  workflow_dispatch:
  schedule:
    - cron: '15 23 * * 3' # UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  flake-update:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout/pull/1707
      - uses: actions/checkout@v4.2.2
        with:
          ref: master
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "SSH private repo auth"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK >/dev/null
          ssh-add - <<< "${{ secrets.SSH_KEY_NIX_SECRETS }}"
          
      - name: "Commit flake.lock updates"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: nix flake update --commit-lock-file

      # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md
      - id: generate-token
        uses: actions/create-github-app-token@v1.11.6
        with:
          app-id: ${{ secrets.PR_APP_ID }}
          private-key: ${{ secrets.PR_APP_KEY }}

      - name: "Pull request & rebase into master"
        id: pull-request
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          TITLE="$(git log --format=%s -n 1)"
          BODY="$(git log --format=%b -n 1)"
          HASH="$(git log --format=%h -n 1)"
          
          git push origin master:flake-update-$HASH
          url=$(gh pr create --base master --head flake-update-$HASH --title "$TITLE" --body "$BODY" --label "nixos") && {
            gh pr merge --rebase --delete-branch --auto "$url"
          } || echo "$(git status)"
